stages:
  - integration-test

integration-test:
  stage: integration-test
  tags:
    - shell
  before_script:
    # - chmod +x ./ci-scripts/setup-database-properties.sh
    - ./ci-scripts/setup-database-properties.sh
    - ./ci-scripts/setup-docker-compose-env.sh
    - docker compose -f ./application/sql/docker-compose.yml up -d
    - ./ci-scripts/run-database.sh $DB_PASSWORD
  script:
    - mvn clean -Dtest=*ITCase test
  after_script:
    - docker compose -f ./application/sql/docker-compose.yml down