stages:
  - test

integration-test:
  stage: test
  tags:
    - shell
  before_script:
    - DB_PASSWORD=$DB_PASSWORD DB_URL=$DB_URL DB_USERNAME=$DB_USERNAME ./ci-scripts/setup-database-properties.sh
    - ./ci-scripts/setup-application-properties.sh
    - DB_PASSWORD=$DB_PASSWORD ./ci-scripts/setup-docker-compose-env.sh
    - docker compose -f ./application/sql/docker-compose.yml up -d
    - cd ./application/sql/
    - docker cp . database:/
    - sleep 3
    - docker exec -i database sh -c "/sh/generate_db.sh $DB_PASSWORD"
    - cd ../..
  script:
    - cd ./application/server/
    - mvn clean -Dtest=*ITCase test
    - cd ../..
  after_script:
    - docker compose -f ./application/sql/docker-compose.yml down