stages:
  - integration-test

integration-test:
  stage: integration-test
  tags:
    - shell
  image: docker:20
  services:
    - docker:dind
  before_script:
    # - chmod +x ./ci-scripts/setup-database-properties.sh
    - ./ci-scripts/setup-database-properties.sh
    - ./ci-scripts/setup-docker-compose-env.sh
    - docker compose -f ./application/sql/docker-compose.yml up -d
    - cd ./application/sql/
    - ls
    # - ./run_database.sh $DB_PASSWORD
    - docker cp . database:/
    - docker exec database sh -c "/sh/generate_db.sh password"
    # - cd ../..
    # - ./ci-scripts/run-database.sh $DB_PASSWORD
  script:
    # - cd ./application/server/
    - mvn clean -Dtest=*ITCase test
    - cd ../..
  after_script:
    - docker compose -f ./application/sql/docker-compose.yml down