stages:
  - integration-test

integrational-test:
  stage: integration-test
  tags:
    - shell
  before_script:
    # - chmod +x ./ci-scripts/setup-database-properties.sh
    - ./ci-scripts/setup-database-properties.sh
    - ./ci-scripts/setup-docker-compose-env.sh
  script:
    - docker compose -f ./application/sql/docker-compose.yml up -d
    - sleep 60
    - ./application/sql/run_database.sh
    - mvn clean -Dtest=*ITCase test
    - docker compose -f ./application/sql/docker-compose.yml down