stages:
  - integration-test

integration-test:
  stage: integration-test
  tags:
    - shell
  before_script:
    # - chmod +x ./ci-scripts/setup-database-properties.sh
    - ./ci-scripts/setup-database-properties.sh
    - ./ci-scripts/setup-docker-compose-env.sh
    - docker compose -f ./application/sql/docker-compose.yml up -d
    - cd ./application/sql/
    - ls
    - cat ./.env
    # - ./run_database.sh $DB_PASSWORD
    - docker logs --tail 50 --follow --timestamps database
    - docker cp . database:/
    - sleep 5
    - docker ps
    - docker logs --tail 50 --follow --timestamps database
    - docker exec -i database sh -c "/sh/generate_db.sh $DB_PASSWORD"
    # - cd ../..
    # - ./ci-scripts/run-database.sh $DB_PASSWORD
  script:
    # - cd ./application/server/
    - mvn clean -Dtest=*ITCase test
    - cd ../..
  after_script:
    - docker compose -f ./application/sql/docker-compose.yml down